### ISSUE TITLE
How to contribute?

### ISSUE THREAD

**Issue by hmharshit** [easyjitsi/docs.easyjitsi.com#1]
How can I get started to contribute in the repository?

**Comment by xceejay** [comment]
Please Contribute By Forking The Repository, Make Your Changes And Create A Pull Request
you can use this [guide](https://github.com/easyjitsi/docs.easyjitsi.com/blob/master/CONTRIBUTING.md)

**Comment by xceejay** [comment]
> How can I get started to contribute in the repository?
Please Contribute By Forking The Repository, Make Your Changes And Create A Pull Request
you can use this guide

**Comment by xceejay** [comment]
> How can I get started to contribute in the repository?

Please Contribute By Forking The Repository, Make Your Changes And Create A Pull Request
you can use this [guide](https://github.com/easyjitsi/docs.easyjitsi.com/blob/master/CONTRIBUTING.md)

**Comment by hmharshit** [comment]
Make some issues on which you need documentation. That'll help a lot to start with.

**Comment by xceejay** [comment]
> Create some issues on which you need documentation. That'll help a lot to start with. I'll look at what I may pick up.

Thanks for the advice:You can see the issue [here](https://github.com/easyjitsi/docs.easyjitsi.com/issues/5)
