### ISSUE TITLE
One line installation does not work

### ISSUE THREAD

**Issue by TobiasJu** [easyjitsi/docs.easyjitsi.com#12]
Hey there,

pretty awesome project you got here, if it works. But sadly i did not get my instance up and running.

I launced an Ubuntu EC2 Instance with 4GB RAM and 2vCores, set up my DNS with Route53 and tried the one liner:  

`sudo /bin/bash -c "$(curl -fsSL https://bash.easyjitsi.com/jitsi/aperture-science-jitsi.info)"`

wich prints the following error msg on the end:

```Plugins selected: Authenticator webroot, Installer None
An unexpected error occurred:
The JWS was signed by a public key the server does not support :: sa.StorageAuthority.KeyBlocked timed out after 5000 ms
Please see the logfiles in /var/log/letsencrypt for more details.
Install Sucessful!😀
```

htop shows many processes with:  
  
```
java -Xmx3072m -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/tmp -Dnet.java.sip.communicator.SC_HOME_DIR_LOCATION=/etc/jitsi -Dnet.java.sip.communicator.SC_HOME_DIR_NAME=jicofo ...
```

**Comment by xceejay** [comment]
Hello, it work - its been tested multiple times on different cloud providers- you might have done something wrong somewhere, can we see your logs?

**Comment by mrostamii** [comment]
It's not your environment's problem. Try again after a while and you would see it's ok.
Actually, it's a problem with Letsencrypt servers. I got the following log and after that it has fixed:
```
The server experienced an internal error :: The service is down for maintenance or had an internal error. Check https://letsencrypt.status.io/ for more details.
```
