### ISSUE TITLE
Feel Free To Contribute To The Documentation

### ISSUE THREAD

**Issue by xceejay** [easyjitsi/docs.easyjitsi.com#5]
Customizing Jitsi Ui(**Unfinished**)
Docker Meets Jitsi(**Unfinised**)
Extending Jitsi(**Unfinised**)
Tips For Deploying Jitsi(**No Content**) 
Other Parts(**You can modify or add content if you find anything wrong or something you can add**)
All Parts(**Translation To Other Languages**)

**Comment by hmharshit** [comment]
I would like to start with adding Jitsi Video Bridge

**Comment by xceejay** [comment]
> I would like to start with adding Jitsi Video Bridge

Yes so fork the repository and create a pull request
